name: "Terraform Plan"
description: "Run terraform plan with support for S3 backend, HCP Terraform Cloud, and artifact upload."

inputs:

  terraform-dir:
    description: "Relative path to the directory containing Terraform configuration files (e.g., 'tf', 'infrastructure')."
    required: false
    type: string
    default: "tf"

  release-tag:
    description: "Git release tag to check out. If omitted, the latest commit on the default branch is used."
    required: false
    type: string
    default: ""

  ci-pipeline:
    description: "Set to 'true' to include the commit SHA in the Terraform state key (suitable for CI/CD). Use 'false' for static state keys."
    required: false
    type: string
    default: "false"

  # Backend Type Selection
  backend-type:
    description: "Backend type to use: 's3' for AWS S3 or 'remote' for HCP Terraform Cloud."
    required: false
    type: string
    default: "s3"

  # Cloud Provider Selection
  cloud-provider:
    description: "Cloud service provider for authentication: 'aws', 'gcp', 'azure', or 'snowflake'."
    required: true
    type: string

  #  AWS S3 Backend Configuration
  s3-bucket:
    description: "Name of the S3 bucket used as the backend for storing the Terraform state file. Required when backend-type is 's3'."
    required: false
    type: string

  s3-region:
    description: "AWS region where the S3 backend bucket is located (e.g., us-east-1, eu-west-1). Required when backend-type is 's3'."
    required: false
    type: string

  s3-key-prefix:
    description: "Optional prefix for the S3 state key (AWS only)."
    required: false
    type: string
    default: ""

  # HCP Terraform Cloud Inputs
  tfc-token:
    description: "HCP Terraform Cloud API token. Should be passed as a secret. Required when backend-type is 'remote'."
    required: false
    type: string

  # AWS Authentication Inputs
  aws-region:
    description: "AWS region for authentication. Required when cloud-provider is 'aws'."
    required: false
    type: string

  aws-role-to-assume:
    description: "AWS IAM role ARN to assume. Required when cloud-provider is 'aws'."
    required: false
    type: string

  # GCP Authentication Inputs
  gcp-wif-provider:
    description: "GCP Workload Identity Federation provider. Required when cloud-provider is 'gcp'."
    required: false
    type: string

  gcp-service-account:
    description: "GCP service account email for authentication. Required when cloud-provider is 'gcp'."
    required: false
    type: string

  # Azure Authentication Inputs
  azure-client-id:
    description: "Azure client ID for authentication. Required when cloud-provider is 'azure'."
    required: false
    type: string

  azure-tenant-id:
    description: "Azure tenant ID for authentication. Required when cloud-provider is 'azure'."
    required: false
    type: string

  azure-subscription-id:
    description: "Azure subscription ID for authentication. Required when cloud-provider is 'azure'."
    required: false
    type: string

  # Snowflake Authentication Inputs
  snowflake-account:
    description: "Snowflake account identifier. Required when cloud-provider is 'snowflake'."
    required: false
    type: string

  snowflake-user:
    description: "Snowflake user name. Required when cloud-provider is 'snowflake'."
    required: false
    type: string

  snowflake-role:
    description: "Snowflake role name. Required when cloud-provider is 'snowflake'."
    required: false
    type: string

  # Snowflake Authentication Secret
  snowflake-private-key:
    description: "Snowflake private key for authentication. Required when cloud-provider is 'snowflake'."
    required: false
    type: string

  # Terraform artifacts
  tf-plan-name:
    description: "Name of the Terraform plan file"
    required: false
    default: "terraform-plan"

  tf-plan-file:
    description: "File to save the Terraform plan output"
    required: false
    default: "tfplan"  

  tf-vars-file:
    description: "Optional Terraform variable file"
    required: false
    default: "terraform.tfvars"

outputs:
  plan-status:
    description: "Result of terraform plan"
    value: ${{ steps.tf-plan.outcome }}

runs:
  using: "composite"
  steps:

    # 📋 Correct Step Sequence:
    ################################################
    # Debug - Print All Inputs - Debug information
    # Validate Configuration - Input validation
    # Set Checkout Ref - Determine checkout reference
    # Checkout Repo - Get the code
    # Setup Terraform - Install Terraform
    # Download Terraform plan artifact - Get the plan file
    # Configure Cloud Authentication - OIDC authentication (AWS/Azure/GCP/Snowflake)
    # Setup TFC Credentials - HCP Terraform Cloud credentials (if remote)
    # Initialize Remote Backend - HCP Terraform Cloud init (if remote)
    # Generate State Key - Create S3 state key (if S3)
    # Initialize S3 Backend - S3 backend init (if S3)
    # Terraform Plan - Execute Terraform plan and save output

    # Print all inputs for debug
    #############################################
    - name: Debug - Print All Inputs
      id: debug-inputs
      shell: bash
      run: |
        echo "=== DEBUG: All Action Inputs ==="
        echo "backend-type: ${{ inputs.backend-type }}"
        echo "cloud-provider: ${{ inputs.cloud-provider }}"
        echo "terraform-dir: ${{ inputs.terraform-dir }}"
        echo "release-tag: ${{ inputs.release-tag }}"
        echo "ci-pipeline: ${{ inputs.ci-pipeline }}"
        echo "tf-plan-name: ${{ inputs.tf-plan-name }}"
        echo "tf-plan-file: ${{ inputs.tf-plan-file }}"
        echo "tf-vars-file: ${{ inputs.tf-vars-file }}"
        echo ""
        echo "=== AWS S3 Backend Inputs ==="
        echo "s3-bucket: ${{ inputs.s3-bucket }}"
        echo "s3-region: ${{ inputs.s3-region }}"
        echo "s3-key-prefix: ${{ inputs.s3-key-prefix }}"
        echo ""
        echo "=== HCP Terraform Cloud Inputs ==="
        echo "tfc-token: [REDACTED - $(if [[ -n '${{ inputs.tfc-token }}' ]]; then echo 'PROVIDED'; else echo 'NOT PROVIDED'; fi)]"
        echo ""
        echo "=== AWS Authentication Inputs ==="
        echo "aws-region: ${{ inputs.aws-region }}"
        echo "aws-role-to-assume: ${{ inputs.aws-role-to-assume }}"
        echo ""
        echo "=== GCP Authentication Inputs ==="
        echo "gcp-wif-provider: ${{ inputs.gcp-wif-provider }}"
        echo "gcp-service-account: ${{ inputs.gcp-service-account }}"
        echo ""
        echo "=== Azure Authentication Inputs ==="
        echo "azure-client-id: ${{ inputs.azure-client-id }}"
        echo "azure-tenant-id: ${{ inputs.azure-tenant-id }}"
        echo "azure-subscription-id: ${{ inputs.azure-subscription-id }}"
        echo ""
        echo "=== Snowflake Authentication Inputs ==="
        echo "snowflake-account: ${{ inputs.snowflake-account }}"
        echo "snowflake-user: ${{ inputs.snowflake-user }}"
        echo "snowflake-role: ${{ inputs.snowflake-role }}"
        echo "snowflake-private-key: [REDACTED - $(if [[ -n '${{ inputs.snowflake-private-key }}' ]]; then echo 'PROVIDED'; else echo 'NOT PROVIDED'; fi)]"
        echo "================================="

    # Validate input configuration
    #############################################
    - name: Validate Configuration
      id: validate-config
      shell: bash
      run: |
        # Validate backend configuration
        if [[ "${{ inputs.backend-type }}" == "s3" ]]; then
          if [[ -z "${{ inputs.s3-bucket }}" || -z "${{ inputs.s3-region }}" ]]; then
            echo "Error: s3-bucket and s3-region are required when backend-type is 's3'"
            exit 1
          fi
        elif [[ "${{ inputs.backend-type }}" == "remote" ]]; then
          if [[ -z "${{ inputs.tfc-token }}" ]]; then
            echo "Error: tfc-token is required when backend-type is 'remote'"
            exit 1
          fi
          echo "Using existing backend configuration from Terraform files"
        else
          echo "Error: backend-type must be either 's3' or 'remote'"
          exit 1
        fi

        # Validate cloud provider configuration
        case "${{ inputs.cloud-provider }}" in
          "aws")
            if [[ -z "${{ inputs.aws-region }}" || -z "${{ inputs.aws-role-to-assume }}" ]]; then
              echo "Error: aws-region and aws-role-to-assume are required when cloud-provider is 'aws'"
              exit 1
            fi
            ;;
          "gcp")
            if [[ -z "${{ inputs.gcp-wif-provider }}" || -z "${{ inputs.gcp-service-account }}" ]]; then
              echo "Error: gcp-wif-provider and gcp-service-account are required when cloud-provider is 'gcp'"
              exit 1
            fi
            ;;
          "azure")
            if [[ -z "${{ inputs.azure-client-id }}" || -z "${{ inputs.azure-tenant-id }}" || -z "${{ inputs.azure-subscription-id }}" ]]; then
              echo "Error: azure-client-id, azure-tenant-id, and azure-subscription-id are required when cloud-provider is 'azure'"
              exit 1
            fi
            ;;
          "snowflake")
            if [[ -z "${{ inputs.snowflake-account }}" || -z "${{ inputs.snowflake-user }}" || -z "${{ inputs.snowflake-role }}" || -z "${{ inputs.snowflake-private-key }}" ]]; then
              echo "Error: snowflake-account, snowflake-user, snowflake-role, and snowflake-private-key are required when cloud-provider is 'snowflake'"
              exit 1
            fi
            ;;
          *)
            echo "Error: cloud-provider must be 'aws', 'gcp', 'azure', or 'snowflake'"
            exit 1
            ;;
        esac

    # Determine checkout reference
    #############################################
    - name: Set Checkout Ref
      id: set-ref
      shell: bash
      run: |
        if [[ -n "${{ inputs.release-tag }}" ]]; then
          echo "ref=${{ inputs.release-tag }}" >> $GITHUB_OUTPUT
        else
          echo "ref=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        fi

    # Checkout repo and setup Terraform
    #############################################
    - name: Checkout Repo
      id: checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ steps.set-ref.outputs.ref }}

    - name: Setup Terraform
      id: setup-terraform
      uses: hashicorp/setup-terraform@v3

    #  Cloud Provider Authentication (OIDC)
    #############################################    
    - name: Configure AWS Authentication (OIDC)
      id: aws-auth
      if: inputs.cloud-provider == 'aws'
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Configure Azure Authentication (OIDC)
      id: azure-auth
      if: inputs.cloud-provider == 'azure'
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Configure GCP Authentication (WIF)
      id: gcp-auth
      if: inputs.cloud-provider == 'gcp'
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ inputs.gcp-wif-provider }}
        service_account: ${{ inputs.gcp-service-account }}

    #  Terraform Cloud Backend 
    #############################################
    - name: Setup Terraform Cloud Credentials
      id: setup-tfc-credentials
      if: inputs.backend-type == 'remote'
      shell: bash
      run: |
        mkdir -p ~/.terraform.d
        cat > ~/.terraform.d/credentials.tfrc.json << EOF
        {
          "credentials": {
            "app.terraform.io": {
              "token": "${{ inputs.tfc-token }}"
            }
          }
        }
        EOF

    - name: Initialize Terraform with HCP Terraform Cloud Backend
      id: terraform-init-remote
      if: inputs.backend-type == 'remote'
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      run: |
        terraform init -input=false

    #  AWS S3 Backend 
    #############################################
    - name: Generate Terraform State Key
      id: generate-tfstate-key
      if: inputs.backend-type == 's3'
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      run: |
        if [[ "${{ inputs.ci-pipeline }}" == "true" ]]; then
          state_key="${{ github.repository }}/${{ github.sha }}/terraform.tfstate"
        else
          state_key="${{ github.repository }}/terraform.tfstate"
        fi
        echo "s3_key=$state_key" >> $GITHUB_OUTPUT

    - name: Initialize Terraform with S3 Backend
      id: terraform-init-s3
      if: inputs.backend-type == 's3'
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      run: |
        terraform init -input=false \
          -backend-config="bucket=${{ inputs.s3-bucket }}" \
          -backend-config="key=${{ steps.generate-tfstate-key.outputs.s3_key }}" \
          -backend-config="region=${{ inputs.s3-region }}" \
          -backend-config="encrypt=true" \
          -backend-config="use_lockfile=true"

    # Final step - Terraform plan and save output
    #############################################
    - name: Terraform Plan and Save Output
      id: tf-plan
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      env:
        # Snowflake environment variables (if cloud-provider is snowflake)
        SNOWFLAKE_ACCOUNT: ${{ inputs.cloud-provider == 'snowflake' && inputs.snowflake-account || '' }}
        SNOWFLAKE_USER: ${{ inputs.cloud-provider == 'snowflake' && inputs.snowflake-user || '' }}
        SNOWFLAKE_ROLE: ${{ inputs.cloud-provider == 'snowflake' && inputs.snowflake-role || '' }}
        SNOWFLAKE_PRIVATE_KEY: ${{ inputs.cloud-provider == 'snowflake' && inputs.snowflake-private-key || '' }}
      run: |
        echo "### Terraform Plan" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        terraform plan -input=false -out=${{ inputs.tf-plan-file }}.out -var-file=${{ inputs.tf-vars-file }}
        terraform show -no-color ${{ inputs.tf-plan-file }}.out > ${{ inputs.tf-plan-file }}.txt
        echo "\`\`\`hcl" >> $GITHUB_STEP_SUMMARY
        cat ${{ inputs.tf-plan-file }}.txt >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

    - name: Upload Plan Output as Artifact
      id: upload-plan-artifact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.tf-plan-name }}
        path: |
          ${{ github.workspace }}/${{ inputs.terraform-dir }}/${{ inputs.tf-plan-file }}.out

    - name: Cleanup Terraform Cloud Credentials
      id: cleanup-tfc-credentials
      if: always() && inputs.backend-type == 'remote'
      shell: bash
      run: |
        rm -f ~/.terraform.d/credentials.tfrc.json
