name: "Terraform Plan"
description: "Run terraform plan with support for S3 backend, HCP Terraform Cloud, and artifact upload."

inputs:
  terraform-dir:
    description: "Relative path to the directory containing Terraform configuration files (e.g., 'tf', 'infrastructure')."
    required: false
    type: string
    default: "tf"

  release-tag:
    description: "Git release tag to check out. If omitted, the latest commit on the default branch is used."
    required: false
    type: string
    default: ""

  ci-pipeline:
    description: "Set to 'true' to include the commit SHA in the Terraform state key (suitable for CI/CD). Use 'false' for static state keys."
    required: false
    type: string
    default: "false"

  backend-type:
    description: "Backend type to use: 's3' for AWS S3 or 'remote' for HCP Terraform Cloud."
    required: false
    type: string
    default: "s3"

  # S3 Backend Inputs
  s3-bucket:
    description: "Name of the S3 bucket used as the backend for storing the Terraform state file. Required when backend-type is 's3'."
    required: false
    type: string

  s3-region:
    description: "AWS region where the S3 backend bucket is located (e.g., us-east-1, eu-west-1). Required when backend-type is 's3'."
    required: false
    type: string

  # HCP Terraform Cloud Inputs
  tfc-organization:
    description: "HCP Terraform Cloud organization name. Required when backend-type is 'remote'."
    required: false
    type: string

  tfc-workspace:
    description: "HCP Terraform Cloud workspace name. Required when backend-type is 'remote'."
    required: false
    type: string

  tfc-token:
    description: "HCP Terraform Cloud API token. Should be passed as a secret. Required when backend-type is 'remote'."
    required: false
    type: string

  tf-plan-name:
    description: "Name of the Terraform plan file"
    required: false
    default: "terraform-plan"

  tf-plan-file:
    description: "File to save the Terraform plan output"
    required: false
    default: "tfplan"  

  tf-vars-file:
    description: "Optional Terraform variable file"
    required: false
    default: "terraform.tfvars"

outputs:
  plan-status:
    description: "Result of terraform plan"
    value: ${{ steps.tf-plan.outcome }}

runs:
  using: "composite"
  steps:
    - name: Set Checkout Ref
      id: set-ref
      shell: bash
      run: |
        if [[ -n "${{ inputs.release-tag }}" ]]; then
          echo "ref=${{ inputs.release-tag }}" >> $GITHUB_OUTPUT
        else
          echo "ref=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        fi

    - name: Checkout Repo
      id: checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ steps.set-ref.outputs.ref }}

    - name: Setup Terraform
      id: setup-terraform
      uses: hashicorp/setup-terraform@v3

    - name: Validate Backend Configuration
      id: validate-backend
      shell: bash
      run: |
        if [[ "${{ inputs.backend-type }}" == "s3" ]]; then
          if [[ -z "${{ inputs.s3-bucket }}" || -z "${{ inputs.s3-region }}" ]]; then
            echo "Error: s3-bucket and s3-region are required when backend-type is 's3'"
            exit 1
          fi
        elif [[ "${{ inputs.backend-type }}" == "remote" ]]; then
          if [[ -z "${{ inputs.tfc-organization }}" || -z "${{ inputs.tfc-workspace }}" || -z "${{ inputs.tfc-token }}" ]]; then
            echo "Error: tfc-organization, tfc-workspace, and tfc-token are required when backend-type is 'remote'"
            exit 1
          fi
        else
          echo "Error: backend-type must be either 's3' or 'remote'"
          exit 1
        fi

    - name: Setup Terraform Cloud Credentials
      id: setup-tfc-credentials
      if: inputs.backend-type == 'remote'
      shell: bash
      run: |
        mkdir -p ~/.terraform.d
        cat > ~/.terraform.d/credentials.tfrc.json << EOF
        {
          "credentials": {
            "app.terraform.io": {
              "token": "${{ inputs.tfc-token }}"
            }
          }
        }
        EOF

    - name: Generate Terraform State Key
      id: generate-tfstate-key
      if: inputs.backend-type == 's3'
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      run: |
        if [[ "${{ inputs.ci-pipeline }}" == "true" ]]; then
          state_key="${{ github.repository }}/${{ github.sha }}/terraform.tfstate"
        else
          state_key="${{ github.repository }}/terraform.tfstate"
        fi
        echo "s3_key=$state_key" >> $GITHUB_OUTPUT

    - name: Initialize Terraform with S3 Backend
      id: terraform-init-s3
      if: inputs.backend-type == 's3'
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      run: |
        terraform init -input=false \
          -backend-config="bucket=${{ inputs.s3-bucket }}" \
          -backend-config="key=${{ steps.generate-tfstate-key.outputs.s3_key }}" \
          -backend-config="region=${{ inputs.s3-region }}" \
          -backend-config="encrypt=true" \
          -backend-config="use_lockfile=true"

    - name: Initialize Terraform with HCP Terraform Cloud Backend
      id: terraform-init-remote
      if: inputs.backend-type == 'remote'
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      run: |
        terraform init -input=false \
          -backend-config="organization=${{ inputs.tfc-organization }}" \
          -backend-config="workspaces=[{name=\"${{ inputs.tfc-workspace }}\"}]"

    - name: Terraform Plan and Save Output
      id: tf-plan
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      run: |
        echo "### Terraform Plan" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        terraform plan -input=false -out=${{ inputs.tf-plan-file }}.out -var-file=${{ inputs.tf-vars-file }}
        terraform show -no-color ${{ inputs.tf-plan-file }}.out > ${{ inputs.tf-plan-file }}.txt
        echo "\`\`\`hcl" >> $GITHUB_STEP_SUMMARY
        cat ${{ inputs.tf-plan-file }}.txt >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

    - name: Upload Plan Output as Artifact
      id: upload-plan-artifact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.tf-plan-name }}
        path: |
          ${{ github.workspace }}/${{ inputs.terraform-dir }}/${{ inputs.tf-plan-file }}.out

    - name: Cleanup Terraform Cloud Credentials
      id: cleanup-tfc-credentials
      if: always() && inputs.backend-type == 'remote'
      shell: bash
      run: |
        rm -f ~/.terraform.d/credentials.tfrc.json
